name: menufy_partner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: ^4.6.5
  google_fonts: ^3.0.1
  readmore: ^2.2.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutter_otp_text_field: ^1.1.1
  firebase_auth: ^4.1.3
  fluid_bottom_nav_bar: ^1.4.0
  animated_toggle_switch: ^0.6.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
